coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "lib/generated/**/*"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "test/**/*"
  - "integration_test/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
